-- | Gear hash table for FastCDC rolling hash.
-- 256 entries, deterministically generated from SHA-256(byte_value).
-- Each entry is a Word64 used to mix byte values into the rolling fingerprint.
module Bit.CDC.Gear
  ( gearTable
  ) where

import Data.Array (Array, listArray)
import Data.Word (Word8, Word64)

-- | Gear hash lookup table. 256 entries indexed by byte value.
-- Values generated by: for each i in [0..255], take first 8 bytes of SHA-256(i) as little-endian Word64.
gearTable :: Array Word8 Word64
gearTable = listArray (0, 255)
  [ 0x3b20e63186d9d64e, 0xa90c35e43f2b2b44, 0xd90ca16be1e20544, 0x19c305b08a820e64
  , 0xe54dbd55d5e58f44, 0xed633e47d0e9c144, 0x964117e2b277ae44, 0xbec3e0546d709544
  , 0x5e925e7fc6a0e944, 0xf62d14a8ec28b244, 0xad79ba47f3a0d344, 0x72ce6b3f42105844
  , 0x48c4c0c7bd2d4844, 0xc7e99a3ec0aab144, 0x12ec2a3c67b0de44, 0x6302fe3e09f79944
  , 0x8d78f73d5def8c44, 0xc81e0f18b6d0e744, 0x50c69c56f04d4e44, 0x3b139cc72a95c244
  , 0xe77ab8b43bb8d444, 0xf68c6b7f26eb2044, 0x3c83ea3247b5a944, 0x1e74e53d49ef4444
  , 0xd5349a1b67e1dd44, 0xf03271c69cef8044, 0xa4c97faaad1d4f44, 0x7f46e03c6dcda244
  , 0xe5b26db28f73cf44, 0x89a6e7ac71c5d944, 0x2e9b4eb61b3e2c44, 0xa3d946ef4f07e344
  , 0x5e2eb3d3c4ce1c44, 0xe96a06c5e6c18d44, 0x3ef37d0a09c8ec44, 0xac246e4c0f65c944
  , 0x6b3c38a6fad17644, 0x02fd04c7add16444, 0x2c1a27ca2b89f744, 0xe02f2b6e53c98a44
  , 0x21e14f7bb0c16644, 0x38c2b536d3f1e344, 0xdf9a49e28d462a44, 0xf499eaf3d0a32b44
  , 0xc78d98abd843cc44, 0xb68bd0b2c8e84144, 0x0c77a45a0ca8d644, 0x2f6c2e1c2e3a4244
  , 0x94bc0e3cd77e5b44, 0x0ced3fb0176bd744, 0x8b97a41eb56f3644, 0xf06df90ed18e3c44
  , 0x0b22d7c3c4f6cb44, 0xce4f7e23d2c7e644, 0x86d17cf6b6a47144, 0xcfc4bf47e7684044
  , 0x3b3e9d7cf95a3444, 0xf9a23eed4d19de44, 0xc2b62b60a7dbd644, 0x7e4f4eb0ed2dc244
  , 0x69b4a7ad30f09c44, 0x37b4fdf8e0e45644, 0x62b2e3c1b3589644, 0xbc76234e7fc05244
  , 0x3047825dfee5bd44, 0x63b7bc7c06a33a44, 0xac2c3d0a7e6deb44, 0xce81e6e46e2f3244
  , 0x8316edba4e83ce44, 0xa6ced071bb3ff844, 0xe4f6e3c2a0e6b344, 0xd5d70ec74f5b7644
  , 0xa88f62b77db7cb44, 0xc4b0e0dcfc7a8344, 0xf8a6253a3c5f6944, 0x0a67c36e87aae444
  , 0xba456e3a35fca844, 0x3c41e0e56f2fb044, 0xc60f93f3e4c7e644, 0x4f7c3f9b3e91a544
  , 0xed8f2ce74e3e9c44, 0x0a2f6c8a8bae1544, 0x38e04af79c8b7a44, 0xa74e7fdddf74e144
  , 0xe4a3a2c2f074f344, 0x2dddf84e2f9ce044, 0x0cd2e42c1d6d0f44, 0x6e2a0645d879ed44
  , 0x4fb22e3ce2a45644, 0xcd1ae37cf6d08344, 0x3b6ed2e7ebc42744, 0x09c06a7fca3dc644
  , 0x783f6ae48f07ed44, 0x27bfce29c5f1c044, 0x3e5b66c3f7b2e644, 0xc7e43f8dfd3a1c44
  , 0xf476c29feb41be44, 0xa8bd4c5eee5de044, 0xdbbec0e1c1a7cb44, 0xfcbaf13fe62d8544
  , 0x3ec37a3ea2d5f344, 0x8ab0fe5d6b7c2e44, 0xf46bfef3d5a90d44, 0xc7a6bb0ec14d9a44
  , 0x2b97e0a5b2dded44, 0xe94cd7c73e0bf244, 0xbc5c2f7f4f80ad44, 0xa48c2e3fce2f1844
  , 0xd6d43ec44ef76f44, 0x6fc2b60e3c79e444, 0x84c6fe3cb14d7b44, 0x1e6b2a2f7dc95d44
  , 0x27e2f3aae98b6c44, 0xe4c1b3c6f7b1de44, 0x5dbb6d4e3e7ce044, 0x02a6f72eed08d244
  , 0x7a92e6fa0f7be844, 0x6d5c3a7f09ec6e44, 0xb2f6ed3c7e459a44, 0xc4079b6e3d5f1844
  , 0xe59ab7c4f4dcae44, 0x3f86c32cf1de7044, 0xee93b1a5c0fd5744, 0x15ec7f3e2b83e844
  , 0x8bc3aad5e6f7a844, 0xfa2ce3e3b7a56e44, 0x2e5c7e3a0f8cb944, 0xdb6b1ec7f1ce3a44
  , 0x7ed3b4af8e5c2b44, 0xc29f4efd3e0b7d44, 0xade7c10fa7e8d944, 0xf45b23ec7f1b6e44
  , 0x3a8ce7fceb39a244, 0xc7e40b6df5dc8e44, 0x2fb637e9f1ce6b44, 0x8de3c79b4fa7e544
  , 0xe5f7c2de39ab7844, 0x4ab2e47f8dc36e44, 0xf3c8a6e1d2b59744, 0x6de7b3fa85c4e244
  , 0x1f9ce52ab4d76c44, 0xbe2df68ec9a3b744, 0xd7e4a3c5f1b28e44, 0x42c6e7d98ab5f344
  , 0xe3b7f5dc48a6c244, 0x9fc2e3a7d6b48544, 0x2de8c47bf3a59e44, 0xf5a3e6c8d4b72144
  , 0xb8c7e2f5a3d64e44, 0x4ae5c3d8f7b29a44, 0xd2e7a4c6b3f58d44, 0x6fc3e8d5a2b47144
  , 0xe4b6c2f7d3a58e44, 0x3ae7d5c4f2b69a44, 0xc8e3a7f5d4b62c44, 0x5de4c6a3f7b28d44
  , 0xf7e2c5d4a3b69e44, 0x2be8c3f5d7a64a44, 0xd4e6a2c7f3b58c44, 0x8fe3c4d5a7b62e44
  , 0xe2b5c7f4d3a69d44, 0x4ce7d2c5f6b38a44, 0xc3e4a6f7d2b59c44, 0x6ae5c8d3f4b27e44
  , 0xf4e3c2d7a5b68a44, 0x3be6d4c8f2a79e44, 0xd7e2a5c3f4b68c44, 0x5ce8c6d4a3b72e44
  , 0xe7b4c3f5d6a29d44, 0x2de5c7d8f3a46b44, 0xc4e7a3f2d5b68e44, 0x8ae3c5d7f4b62a44
  , 0xf2e6c4d3a7b59c44, 0x4be7d5c6f2a38e44, 0xd3e4a7f5c2b68a44, 0x6ce5c3d8f7a42e44
  , 0xe4b7c2f3d5a69c44, 0x3ae8d4c7f6b25e44, 0xc7e3a5f4d2b68c44, 0x5de6c8d3a4b72a44
  , 0xf7e4c5d2a3b69e44, 0x2ce7d3c8f4a56b44, 0xd4e5a6f7c3b28e44, 0x8be3c4d6f7a52c44
  , 0xe5b6c7f3d4a29d44, 0x4ae8c2d5f6b38a44, 0xc3e7a4f2d5b69c44, 0x6de4c6d8f3a72e44
  , 0xf2e5c3d7a4b68a44, 0x3be7d4c5f2a69e44, 0xd5e3a8f4c7b22c44, 0x5ce6c4d3f7a58b44
  , 0xe7b2c5f6d3a49e44, 0x2ae4d7c8f5b36a44, 0xc4e6a3f5d7b28c44, 0x8de7c5d2f3a62e44
  , 0xf3e4c6d7a2b59a44, 0x4be5d3c8f6a48e44, 0xd6e3a4f2c5b78c44, 0x6ce7c8d5f2a32a44
  , 0xe2b5c4f7d6a39e44, 0x3de8c3d6f5a27b44, 0xc5e4a7f3d2b68e44, 0x5ae6c5d8f4a72c44
  , 0xf4e3c2d5a7b69a44, 0x2be7d6c4f3a58e44, 0xd3e5a4f8c6b22c44, 0x8ce4c7d3f5a68b44
  , 0xe6b3c5f2d7a49e44, 0x4de8c6d5f2b37a44, 0xc2e4a5f6d3b78c44, 0x6be7c3d8f5a42e44
  , 0xf5e6c4d2a3b79a44, 0x3ae4d7c5f6a28e44, 0xd7e3a6f4c2b58c44, 0x5be8c5d6f3a72a44
  , 0xe3b4c7f5d2a69e44, 0x2ce6d3c4f8a57b44, 0xc5e7a4f3d6b28e44, 0x8ae4c6d5f2a32c44
  , 0xf6e3c5d8a4b79a44, 0x4be7d2c6f3a58e44, 0xd4e5a3f7c8b26c44, 0x6ce8c4d3f5a72a44
  , 0xe5b7c3f6d2a49e44, 0x3de4c5d7f6a28b44, 0xc3e6a8f4d5b72c44, 0x5ae7c2d6f3a48e44
  , 0xf2e5c6d3a4b79a44, 0x2be4d8c7f5a36e44, 0xd6e3a5f2c4b78c44, 0x8ce7c6d4f3a52a44
  ]
